services:
  # 1. Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mathforum_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend .NET 9
  backend:
    build: ./backend
    container_name: mathforum_backend
    ports:
      - "${BACKEND_LOCAL_PORT}:8080" # Map port 5293 -> 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
     
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
  
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj

  # 3. Frontend React Vite
  frontend:
    build: ./frontend
    container_name: mathforum_frontend
    ports:
      - "${FRONTEND_LOCAL_PORT}:5173"
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_LOCAL_PORT}/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  
      - /app/node_modules

volumes:
  postgres_data: